### ISSUE TITLE
Not working to change Awake status

### ISSUE THREAD

**Issue by jploo** [pgerke/streamdeck-awake#1]
The plugin installs fine, but does not appear to be working to change the status of Awake. I know there were some changes to Awake with the latest version of PowerToys, so maybe it is related to that. Tapping the key toggles between the three states (eye, question mark, red slash). It doesn't matter if I use the default executable path (which is correct), or if I set it to the absolute path of the Awake executable.

Windows 11
PowerToys v0.51.0
Stream Deck 5.1.3.14750

Let me know if there is any additional info I can provide. Thank you!

**Comment by pgerke** [comment]
Strange... I upgraded to PowerToys 0.51.0 and it's still working for me... Do you by chance have Awake enabled in the PowerToys? 
I keep it disabled in the PowerToys, because I'm triggering the executable with the plugin. When I activate Awake in the PowerToys I'm getting the behavior you described. And what's worse, even when I disable Awake in the PowerToys again, the plugin remains broken until I restart the Stream Deck Tool. 
So the plugin seems to crash when Awake is enabled in the PowerToys. That's a bug alright...

**Comment by jploo** [comment]
Ah I see, I misunderstood how it was supposed to work. Ok yes, when I disable Awake in PowerToys then restart Stream Deck I am able to get it to work.

This could be a different Issue, but I did notice that there aren't options for --use-pt-config, --display-on, or --time-limit. Looks like some of these exist in the Settings class but are commented out in the UI. Is there a way I can make those work?

**Comment by jploo** [comment]
I fixed the settings issue in #2
